# Generated by Django 6.0.4 on 2026-04-30 14:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=50)),
                ('asignatura', models.CharField(max_length=255)),
                ('nota1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('promedio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5)),
            ],
        ),
    ]
